### ISSUE TITLE
Can't set `mupdf-gl` as custom view command

### ISSUE THREAD

**Issue by specter119** [mronkko/ZoteroQuickLook#11]
os version: macOS 10.13.2/windows 10 1709 16299.64
Zotero version: 5.0.30
ZoteroQuickLook version: 1.13.2

[log gist](https://gist.github.com/specter119/79e67fe5b9f6f59eda6389db6a58a624)

I can open pdf with 

```
mupdf-gl <pdf_file_name>
```

 in console, and set `extensions.zoteroquicklook.customviewcommand` with full path of `mupdf-gl`, but it failed to open pdf with `mupdf-gl`.

update: I also test it on win10, it seems that related to mupdf. this plugin performs well with SumatraPDF on windows. I guess it may related to the path of attachment?

**Comment by bwiernik** [comment]
Zotero QuickLook isn't intended to open a file in a particular PDF program, but rather to preview files using a quicklook program. macOS comes preloaded with a quicklook program, and you should not use the custom view command on Mac. If you want to change what PDF program is used to open files in Zotero, set that using the option in Zotero's General preferences, not with this plugin.
