### ISSUE TITLE
Quicklook 0.3.2 wont open file

### ISSUE THREAD

**Issue by jorjio** [mronkko/ZoteroQuickLook#12]
Hi!

I'm filling the directory and executable in the extensions.zoteroquicklook.customviewcommand
in my case its : C:\Program Files (x86)\QuickLook\QuickLook.exe
but i get a message that quicklook is already running.
i tried to add %1, and use quotation marks. i also tried to disable the extensions.zoteroquicklook.usefilenameworkaround
what am i missing?

BIG thanks!

**Comment by bwiernik** [comment]
What quicklook program are you trying to use?

**Comment by jorjio** [comment]
uninstalled - reinstalled the extension and quicklook - and now it works.
sorry for not closing this "issue "before..

thanks!
