### ISSUE TITLE
QL fails if item has a Zotero note

### ISSUE THREAD

**Issue by bwiernik** [mronkko/ZoteroQuickLook#16]
If a note is listed above the attachment PDF file in Zotero's file tree, quicklook fails. Deleting the note allows the PDF to be previewed as expected.

**Comment by hjr0** [comment]
I encountered this problem too. Help needed.

**Comment by bwiernik** [comment]
This appears to no longer be the case on Windows.

**Comment by bwiernik** [comment]
Also appears to be resolved on Mac.
