### ISSUE TITLE
how to use windowsApps "QuickLook" in ZoteroQuickLook?

### ISSUE THREAD

**Issue by BenjaminDbb** [mronkko/ZoteroQuickLook#17]
I have Windows Store Version QuickLook. 
When I use ```space``` to preview. Show I have no right
What should I do?

**Comment by bwiernik** [comment]
You need to set the `extensions.zoteroquicklook.customviewcommand` preference to point at the executable for the Windows Store QuickLook app. I recommend just using the MSI version available from GitHub, as it is easier to install and setup and updated more frequently.
