### ISSUE TITLE
Link in project description is broken (redundant?)

### ISSUE THREAD

**Issue by daviewales** [mronkko/ZoteroQuickLook#19]
The following link appears in the project description:

https://addons.mozilla.org/en-US/firefox/addon/zoteroquicklook/

**Comment by bwiernik** [comment]
I'm not sure where you are saying this link is shown. I don't see it anywhere. Can you give a specific URL?

**Comment by daviewales** [comment]
The link appears at the top of this page. (Not in the Readme.)

https://github.com/mronkko/ZoteroQuickLook

**Comment by bwiernik** [comment]
Ah, got it. @mronkko Could you delete that? I can't edit the description.

**Comment by mronkko** [comment]
I deleted the link. Was there an alternative link that I should add?

**Comment by bwiernik** [comment]
No, releases through this repository is how the plugin is being served now, and that seems to be working fine.
