### ISSUE TITLE
Alternative build for Windows

### ISSUE THREAD

**Issue by qqobb** [mronkko/ZoteroQuickLook#22]
I recently started using version 1.4.0 of ZoteroQuickLook without problems. Thanks a lot for this great add-on!

I'm using an alternative viewer and the 'customviewcommand' setting on Windows 10. Now I noticed that version 1.4.1 is including a 'Bridge.exe' binary file. I understand that this should enable support for the Windows Store QuickLook program. That's certainly great for users of that software. But I would appreciate it if you could make this optional and provide a version without the file. There have been some (false positive) threats [reported](https://github.com/QL-Win/QuickLook/issues/561), and I would feel more comfortable recommending ZoteroQuickLook to others if there was a build without the exe file. I could try to help with the additional work that would be required.

If I understand @dstillman's [comment](https://github.com/mronkko/ZoteroQuickLook/pull/21#issuecomment-561117062) correctly, the "unpacked" flag is not used in Fx60, such that the two builds 'zoteroquicklook.zoteroplugin' and 'zoteroquicklook-altwindows.zoteroplugin' currently provided are no longer really different. So a suggestion would be to keep providing two builds, but to only include 'Bridge.exe' in 'zoteroquicklook-altwindows.zoteroplugin'. Users of the Windows Store version of QuickLook could then be referred to this version.

Note that I'm not writing on the Zotero forum since this is a rather technical issue.

**Comment by bwiernik** [comment]
You make a good point that the unpacked altwindows version isn't necessary anymore.

Regarding Bridge.exe, the source code for the file is included on this repository an in the release file. It is clear exactly its contents and that there isn't anything nefarious there. You are of course welcome to inspect the EXE and see that it aligns with the source code (for a .NET decompiler for this purpose, see https://github.com/icsharpcode/ILSpy). The false positive you link to isn't relevant; that was a false positive for a component of the QuickLook MSI itself, which is version of the program you are already running. 

Using the Bridge script enables one simple workflow to be used by ZoteroQuickLook to connect to both versions of QuickLook. Avoiding it would require two completely different internal scripts, which would substantially increase the maintenance requirements.
