### ISSUE TITLE
QuickLook configuration in Linux

### ISSUE THREAD

**Issue by bakulaibuji** [mronkko/ZoteroQuickLook#34]
Now Linux provide a similar function with "QuickLook" in Windows called "GNOME Sushi". But in Linux (mine is Ubuntu 20.04), how to configure the "QuickLook" Plugin in zotero to use the "GNOME Sushi"?

**Comment by fengmao31** [comment]
i need it too

**Comment by bwiernik** [comment]
See here https://github.com/mronkko/ZoteroQuickLook/issues/23#issuecomment-735219371

I don’t have a Linux machine to test on. If someone submits a pull request changing that Linux default to GNOME Sushi, I will merge it.
