### ISSUE TITLE
Crush: Windows can not access the specified file...

### ISSUE THREAD

**Issue by CodeAunt** [mronkko/ZoteroQuickLook#36]
on Windows 10 Zotero  
I had used it for several days fluently
But after I pressed the space today I got this 
![image](https://user-images.githubusercontent.com/30389296/102587581-0ce8d100-4147-11eb-9a1b-b4ec673ecc05.png)
It doesn't work for all the documents in Zotero but it works fine in explorer. 
I have confirmed that the config to the .exe file is correct.
And I have tried to start the QuickLook with administrator permission.

**Comment by bwiernik** [comment]
Definitely don’t use administrator privileges anywhere. If you installed Zotero with admin status (if it asks you to approve each time it launches), uninstall and reinstall Zotero. Can you start by removing and reinstalling the plugin from Zotero?

**Comment by CodeAunt** [comment]
> Definitely don’t use administrator privileges anywhere. If you installed Zotero with admin status (if it asks you to approve each time it launches), uninstall and reinstall Zotero. Can you start by removing and reinstalling the plugin from Zotero?

I solve this through uninstall the Windows Store version and install the released msi version Quicklook, Thanks a lot!
