### ISSUE TITLE
html snapshots appear as code

### ISSUE THREAD

**Issue by jeron1** [mronkko/ZoteroQuickLook#37]
This is on linux with gloobus-preview. PDF previews fine.

**Comment by bwiernik** [comment]
Do they appear how you expect if you preview them directly from the file system?

**Comment by jeron1** [comment]
Hi, yes, the preview of a such an html snapshot shows code similarly in Dolphin, although in Dolphin it word-wraps. (The html snapshot of course views fine when double clicked to open in a browser, e.g., Vivaldi.)

**Comment by bwiernik** [comment]
This isn't anything the Zotero plugin can fix then--all the Zotero plugin does is call gloobus-preview. You would need to install a plugin to gloobus for it to handle HTML files better. Some other Linux users have had success setting up gnome-sushi instead. https://github.com/mronkko/ZoteroQuickLook/issues/23

**Comment by jeron1** [comment]
I did give an initial try to sushi earlier, but I didn't see support #23 about using it (which I will check out now). I appreciate the responses.
