### ISSUE TITLE
Quicklook not working with sushi

### ISSUE THREAD

**Issue by Allanmarbaniang** [mronkko/ZoteroQuickLook#39]
I'm running Ubuntu 20 and I can't seem to find a working Gloobus-Preview. So I'm using sushi for QuickLook. But Zotero Quicklook plugin does not seem to work when I press space on a document.

I have kept `/usr/bin/sushi` in the extensions.zoteroquicklook.customviewcommand

**Comment by ventolinmono** [comment]
Running Debian 10 and I also cant seem to find how to make Quicklook work with Sushi with the extensions.zoteroquicklook.customviewcommand.

Tried this on the terminal and it worked:

`dbus-send --print-reply --dest=org.gnome.NautilusPreviewer /org/gnome/NautilusPreviewer org.gnome.NautilusPreviewer.ShowFile string:file:///home/user/folder/file.png int32:0 boolean:false`

But I'm not sure what to type on the Value field of extensions.zoteroquicklook.customviewcommand. Can you help me with this please?

With the correct value should Quicklook work with Sushi by selecting a Zotero item and then pressing space bar?

**Comment by pankus** [comment]
Same problem here with Ubuntu 20.04

**Comment by bwiernik** [comment]
If some submits a pull request replacing gloobus as the default with sushi, I will merge it.

**Comment by ventolinmono** [comment]
Thanks. How is this? Can I do it?

**Comment by bwiernik** [comment]
Fork the repository and make the changes in your fork. Test them out. If they work, open a pull request.

**Comment by bwiernik** [comment]
The plugin should work with sushi by default now as of https://github.com/mronkko/ZoteroQuickLook/pull/42

**Comment by ventolinmx** [comment]
Sorry, installed latest release but it's still not working.

**Comment by lbc1027** [comment]
你好，邮件已收到，我会尽快处理，如有急事请联系13547906739
