### ISSUE TITLE
Zotero 5

### ISSUE THREAD

**Issue by jamespl87** [mronkko/ZoteroQuickLook#9]
Any chance of a revision to this plugin to make it compatible with Zotero 5 beta? Thanks.

**Comment by atanasj** [comment]
Yes please!

**Comment by alireza3335** [comment]
Hope to be able to use this great feature in Zotero 5.

**Comment by emeryl** [comment]
Another GitHub user has forked this plugin and updated it for use with Zotero 5.
See discussion [here](https://forums.zotero.org/discussion/63473/zotero-5-beta-r91-quicklook)
And [here's the updated version](https://github.com/bwiernik/ZoteroQuickLook) on GitHub

**Comment by mronkko** [comment]
Please create a pull request and I will update the package on Mozilla extensions directory.

**Comment by gracile-fr** [comment]
poke @bwiernik

**Comment by bwiernik** [comment]
PR: https://github.com/mronkko/ZoteroQuickLook/pull/10

**Comment by mronkko** [comment]
Fixed
